### ISSUE TITLE
Add community widgets section to docs

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-website#1]
In the long term we'll likely put a lot of work into creating a place for discovering community extensions. This is not that.

This ticket covers the immediate need to surface community contributed widgets for maximum visibility and with minimal effort.

I propose we add a "Community Widgets" section to the Widgets page in the docs. It would be identical to the "Widgets" section, with a cloud of widget names and individual markdown files for each widget. We'd generally expect widget authors to submit a PR with documentation for their widget.

Thoughts?

**Comment by zebapy** [comment]
Not sure if I was previously assigned here, but I don't have the bandwidth now. Sorry folks!

**Comment by martinjagodic** [comment]
I am closing this because there are not many community widgets out there. If you find this issue and you have something to list, let me know, and I would be glad to reopen this.
