### ISSUE TITLE
Docs require fundamental infrastructure overhaul to fully integrate with CI/CD pipeline.

### ISSUE THREAD

**Issue by silverwebb925** [decaporg/decap-website#12]
### **Is your feature request related to a problem? Please describe:**
Yes. The Docs will _never_ stay up-to-date or comprehensive enough with the existing documentation development pipeline.

Individual section/articles have excellent content (barring minor outdated items), but what I’m seeing* implies that while the project has a good CI/CD pipeline for features and bugs, the Docs themselves are progressing almost as a separate development stream that has a more traditional trajectory. Conceptually, the current PR process _should_ keep the Docs updated... but the pipeline doesn't have enough built-in validation to really _ensure_ that the docs stay up-to-date with the state of the CMS.

I can already tell that everyone is onboard to bring the Docs up to speed, but I really must emphasize that _**good documentation and smooth documentation workflow is essential to the sustainability of this project.**_ The accessibility of the Docs is directly tied to NetlifyCMS adoption, and the Docs provide a major route to bring new contributors into the fold (here I am, after all).

*I've read through the GitHub Issue archive pretty extensively, specifically paying attention to reorganization efforts related to the Docs, and have listed the most relevant issues under Additional Context at the end. Please let me know if there are additional issues to add for reference.

**Personal Note:**

> I have a professional background in technical graphic design and master planning/documentation, as well as significant experience automating complex design/documentation tasks via JavaScript… but I've only recently begun pursuing  software engineering as a career. Please forgive _and correct_ me if ever fail to grasp something you might consider basic in terms of CS or NetlifyCMS itself. I am a strong believer in RTFM, and appreciate any links or resources you want to share. Thank you!

### **Describe the solution:**
I propose that fully integrating the documentation pipeline with the rest of the project's CI/CD should jump to (near) the top of the list for NetlifyCMS development priorities, and that only the bare-minimum of manual effort be expended to reorganize or revise the Docs within the current infrastructure. Once a more robust content schema and contribution workflow is in place, reorganizing and updating the docs happen as a matter of course and it will happen much faster and more accurately than it can now.

I have a lot of ideas regarding Docs design, organization, content, and workflows, but here’s a first-pass at big-picture goals and a more granule task list as a potential place to start.

**Ranked Big-picture Goals:**
I. Establish Docs master schema to bring content into alignment across sections and articles.
II. Establish prescriptive content standards applied through automated validation.
III. Revise the backend CMS configuration to extend Open Authoring capabilities while maintaining content schema.
IV. Revise the frontend Docs UI to aid navigation and improve UX, including no-investment feedback options.

**Possible Initial Task List**
- [x] 1. Incorporate documentation linting as a standard test for all PR’s. Even if the linter’s output still requires human attention, it will at least begin providing metrics validating both the integrity of the Docs and conversely helping to ensure future content will align with previously established standards. Is there a linter that is specific to validating NetlifyCMS code that could be adapted to run on the Docs as well? PR Opened for this step: decaporg/decap-cms#4320
- [ ] 2. Tie documentation linting to automated Docs content updates, flagging automatic changes for manual review. Start small, such as updating syntax of fields, such as changing value_field to valueField.
- [ ] 3. Incorporate basic tracking data into articles, including automatically tagging articles with original submission date, date of last update, last validation date (and PR#?), history of last few authors (including bots), NetlifyCMS version compatibility, etc. Exposing some of this tracking data to the Docs end users should help drive confidence in the efficacy of the Docs and create a basis for better feedback when items can easily be verified to be out of date.
- [ ] 4. Increase user feedback by implementing no-investment feedback options. No sign-in article flagging, etc.
- [ ] 5. Improve the Open Authoring workflow by exposing more settings to non-technical users. 

[This article](https://opensource.com/business/15/7/continuous-integration-and-continuous-delivery-documentation) highlights many of the advantages I would expect to see from implementing documentation linting.

I am unfamiliar with implementing or customizing linters, and only just discovered they already exist for documentation (it’s always validating to find out someone has built and is using something you’ve only just dreamed up).
I would love to hear from more experienced contributors about the idea of overhauling the entire process of documentation and if documentation linting is the right place to start.

——————————————
A few more ideas that are related to the big picture goals I am suggesting.

**Content Schema**
In general, I’d ideally like to see the configuration of the Docs CMS much more abstracted, if not completely decoupled from the page layouts the users see.
It will always be important to see and edit articles in a WYSIWYG fashion, but perhaps each article is implemented via a content template with the individual fields correlated across articles. Consistency versus flexibility will be an interesting balance, but most documentation really can be broken down into a finite set of information modes allowing for a consistently implemented schema. In terms of the existing Docs, a good example of this cross-correlation is that many articles are already loosely following this structure:

- Concepts
- Tech Specs
- Tutorial
- Advanced Options

So instead of choosing between writing articles in a mode suitable for every user group or writing articles that leave out user groups... what if content was abstracted and (more) standardized so it could be compiled differently for each user groups (Designers, Engineers, Authors, Contributors, etc). Likewise, this information could be edited across articles more easily… for example, maybe I’m only interested in ensuring a consistent voice across all Concept sections. I could fire up the Concepts Glossary, and scroll through all the article headings at once with the preview pane showing the full context for any entry I'm actively editing.

**UI Design Thoughts**
Navigating the Docs is somewhat cumbersome on each of the front and back ends, and both could use UI changes to improve the UX. I’m trying to avoid extensive brainstorming about the CMS UI for the moment because improvements to the Docs Open Authoring experience might be better addressed by working through the Issues captured in the in-progress UX Project related to decaporg/decap-cms#2557... and a lot of the CMS UI might be dictated by whatever content schema is adopted.

Here are some specific UI/UX ideas for the frontend:
I visited [docs.netlify.com](https://docs.netlify.com/) for the first time today and realized I basically described that UI.
Is it possible to source/port and adopt the UI directly from docs.netlify.com? Restyled to match the NetlifyCMS branding of course.
This would remove a _lot_ of work from revamping the Docs frontend, and shouldn't cost Netlify.com anything to provide the existing design files, right?

### **Additional Context - Related Issues:**
**Docs Content & Org**
decaporg/decap-cms#598 - Build a more organized outline for docs
decaporg/decap-cms#1038 - Improve contributing guidelines (OPEN)
decaporg/decap-website#2 - Create a user guide for content editors (OPEN)
decaporg/decap-cms#1632 - Add a style guide to documentation contributor info
decaporg/decap-website#5 - Reorganize the docs with a strong focus on the user (OPEN)
decaporg/decap-cms#2336 - Improve Contrib Guide and Create Style Guide
decaporg/decap-website#10 - A proposal for reorganizing the NetlifyCMS Docs navigation (OPEN)
decaporg/decap-cms#3766 - feat: reorganizing the NetlifyCMS Docs navigation

**Structured Testing**
decaporg/decap-cms#1013 - Determine testing strategies

**UX Design**
decaporg/decap-cms#2557 (OPEN Project)

**Comment by privatemaker** [comment]
The comms eco-system around Github has changed since this was filled, there are Issues or [Discussions](https://github.com/decaporg/decap-cms/discussions). There is an automated build process for the documentation now. AFAICT a linter was added...

Is this issue still relevant?

**Comment by martinjagodic** [comment]
I agree. There are some good ideas here, but they are not aligned with our current focus. Closing.
