### ISSUE TITLE
Add guide for using Decap CMS with Vue / VitePress

### ISSUE THREAD

**Issue by privatemaker** [decaporg/decap-website#31]
We need an easy to follow `Platform Guide` for [VuePress](https://vuepress.vuejs.org) the Vue-powered static site generator.

Highlighted in [comment](https://github.com/decaporg/decap-website/issues/6#issuecomment-1924195221) there is a shakeup between `VuePress` and many migrating to `VitePress` so i'm not sure which guide makes more sense as I don't use either project. Maybe @aentwist can comment?

Issue split out of #6

**Comment by martinjagodic** [comment]
Since there is not much recent activity on the VuePress repo, I would go with VitePress. We're probably writing these guides for the long term so it would be a shame to start with a deprecated tool.
