### ISSUE TITLE
Search feature is broken due to it linking to the old website

### ISSUE THREAD

**Issue by caendesilva** [decaporg/decap-website#39]
All Algolia search results at https://decapcms.org/ are broken as they lead to the old domain.

**Comment by martinjagodic** [comment]
We are aware of this problem, but Algolia is super unresponsive. Actually, there are 2 problems:

- netlifycms.org domain is not redirected to decapcms.org anymore. It stopped working when we transferred we website to its own repo. We are working on restoring this redirect.
- Algolia search property was never transferred to us. We want to open our docsearch property but we get no response from them. We've tried a few times already :(

**Comment by caendesilva** [comment]
> We are aware of this problem, but Algolia is super unresponsive. Actually, there are 2 problems:
> 
> * netlifycms.org domain is not redirected to decapcms.org anymore. It stopped working when we transferred we website to its own repo. We are working on restoring this redirect.
> * Algolia search property was never transferred to us. We want to open our docsearch property but we get no response from them. We've tried a few times already :(

Oh man that's a real bummer. Maybe the search input should be hidden for now? It doesn't seem like any part of it works. Maybe you need to create a new Algolia search property if they are unwilling to transfer it?

**Comment by privatemaker** [comment]
Is signing up for a "new Algolia search property" the best route? After 10k searches, they charge money. Do we really need AI analysis of 50 - 100 pages of docs- me thinks not 🤷🏻‍♀️ ?!

There are a few JS libs that require ZERO third-party service signup and just execute between server and client's browser. This seems wiser IMHO. 

- [Lunar.js](https://lunrjs.com) i've used before with Hugo and it's nice. There is a [gatsby-plugin-lunar](https://github.com/humanseelabs/gatsby-plugin-lunr)
- [Elasticlunr.js](https://github.com/weixsong/elasticlunr.js), also sounds good.

Both seem unmaintained, but maybe that's not a big deal.

[Fuse.js](https://github.com/krisk/Fuse) is actively maintained. I have no experience with it, but there's also an actively maintained [gatsby-plugin-fusejs](https://github.com/johnny-mh/blog2/tree/main/packages/gatsby-plugin-fusejs) package. 

I know @razonyang has worked with Fuse.js, maybe they can comment with some thoughts?

> Maybe the search input should be hidden for now?

This might be for the best, for now 😬

**Comment by razonyang** [comment]
I'd recommend [applying a new DocSearch property](https://docsearch.algolia.com/apply), and replace `apiKey` and `indexName` after getting approval.

> After 10k searches, they charge money.

That's true for Algolia search, but not for _Algolia DocSearch_. As I know, [_DocSearch_ is entirely free and automated](https://docsearch.algolia.com/docs/what-is-docsearch#how-to-feature-docsearch) for open source/technical site/blog.

**Comment by caendesilva** [comment]
Yeah it's been maybe 2 years since I used Algolia, but back then they sponsored plans for open source projects and I assume it's still the same.

**Comment by martinjagodic** [comment]
> I'd recommend [applying a new DocSearch property](https://docsearch.algolia.com/apply), and replace `apiKey` and `indexName` after getting approval.

We applied half a year ago and last week and got no response. It appears we will have to go with Algolia Netlify Crawler.
