### ISSUE TITLE
We need guides.

### ISSUE THREAD

**Issue by erquhart** [decaporg/decap-website#6]
We need to write a whole lot of guides and pile them into the docs.

Let's keep a list of topics here. Suggest topics via comments, use reactions to +1 your favorites.

---

**General**
- [ ] Controlling Filenames
- [ ] Common Errors
- [ ] Troubleshooting
- [ ] Using with CSS-in-JS (some good solutions in https://github.com/netlify/netlify-cms/issues/793)
- [ ] Working with Images
- [x] Publishing with Editorial Workflow
- [x] Authentication, including all options and Git Gateway w/o Netlify

**Authentication**
- [ ] Working with self hosted `git-gateway`, `go-true` (possibly with SSO). [Possible reference](https://github.com/hfte/netlify-cms-with-selfhosted-gotrue-and-git-gateway).

**Static Site Generators**
- [x] Using Netlify CMS with Jekyll
- [x] Using Netlify CMS with Hugo
- [x] Using Netlify CMS with Gatsby
- [x] Using Netlify CMS with Next
- [ ] Using Netlify CMS with Hexo
- [ ] Using Netlify CMS with VuePress
- [x] Using Netlify CMS with Nuxt
- [x] Using Netlify CMS with Docusaurus
- [x] Using Netlify CMS with Middleman
- [ ] Using Netlify CMS with Eleventy

**Comment by privatemaker** [comment]
Hey everyone 👋🏻  in the spirit of our efforts re-booting Decap CMS and various documentation sprints, I've triaged all the missing guides from this list for easier tracking and coordination and closing this issue. 

If any of you who mentioned contributing in the past (we realize it's quite a few years ago now), were interested we'd love your contributions, specifically:

- @nikosolihin @ZoltanVeres #33 
- @brentjayingram #35
- @aentwist #31 

Also feel free to pop by [our Discord server](https://decapcms.org/chat) to connect!
